server:
  servlet:
    context-path: /api
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:postgresql://localhost:9876/evidentor
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
